# Generated by Django 5.2 on 2025-04-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSCostQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('granularity', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AWSCostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.CharField(max_length=100)),
                ('environment', models.CharField(blank=True, max_length=100, null=True)),
                ('blended_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unblended_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usage_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_data', to='amazon.awscostquery')),
            ],
        ),
    ]
